[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node backend/server.js & node bot/bot.js & wait"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
